alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ls='ls --color=auto'
alias la='ls -la'
alias l='la'
alias mcilog='vi ~/tmp/mci'
alias mi='mvn install > ~/tmp/mci;tail ~/tmp/mci'
alias mci='mvn clean install > ~/tmp/mci;tail ~/tmp/mci'
alias mci_jdk7='JAVA_HOME=~/programs/jdk1.7.0_05/ mci'
alias mci-skiptests='mvn -Dmaven.test.skip=true clean install > ~/tmp/mci;tail ~/tmp/mci'
alias mci_jdk7-skiptests='JAVA_HOME=~/programs/jdk1.7.0_05/ mci-skiptests'
alias mci-offline='mvn -o clean install > ~/tmp/mci;tail ~/tmp/mci'
alias mci_jdk7-offline='JAVA_HOME=~/programs/jdk1.7.0_05/ mci-offline'
alias mci-offline-skiptests='mvn -o -Dmaven.test.skip=true clean install > ~/tmp/mci;tail ~/tmp/mci'
alias mci_jdk7-offline-skiptests='JAVA_HOME=~/programs/jdk1.7.0_05/ mci-offline-skiptests'
alias dep-tree='mvn dependency:tree > ~/tmp/dep-tree && vi ~/tmp/dep-tree'
alias work='cd ~/workspace'
alias tmp='cd ~/tmp/'
alias mkdir='mkdir -pv'
alias stashgup='git stash;git pull;git stash pop'
alias less='less -r'
alias psg='ps aux|grep'
alias diff='diff -u -U 0 -a -w --ignore-blank-lines'
